### PR TITLE
explorer

### PR DESCRIPTION
**Pull request by marqh**
replacement for browse, using an object to manage the interface

### CODE REVIEW

**Comment by marqh** [comment]
replaces #60

**Comment by marqh** [comment]
@corinnebosley please let me know your opinion on this

**Comment by corinnebosley** [comment]
Looks good to me.  I actually find it easier to understand the interactions in this form, because you can clearly see which things you have to define to begin with (things in _init_) and which things prompt a change (things in functions).

I am happy with the extra line to call it, I think this is a minimal change which is more than justified.

**Comment by corinnebosley** [comment]
Happy to merge.  You want Bill to see it before I go ahead?

**Comment by marqh** [comment]
> Happy to merge. You want Bill to see it before I go ahead?

i don't think it's necessary, as long as you are content and that you've checked you can run it effectively

**Comment by corinnebosley** [comment]
How do I run it before it's merged? Do I have to checkout your branch and then run it from there?

**Comment by marqh** [comment]
> How do I run it before it's merged? Do I have to checkout your branch and then run it from there?

yes

**Comment by corinnebosley** [comment]
Before you changed this, when I ran the import statement, all the options appeared (a bit like a GUI).  Now, with the extra line, I can't seem to work out what I need to do.  I can run the file with no errors, but I don't get any output or widgets.

**Comment by marqh** [comment]
try:
```
import cube_browser.explorer
exp = cube_browser.explorer.Explorer()
```

**Comment by corinnebosley** [comment]
@marqh  Fixed my versions issue.  Can now see the stuff that happens when you run that code.  

Still getting an invalid selection error when I try and load a cube though.  Is that an issue to be solved in another PR or do you want it fixed before I merge this?

**Pull request merged**
