### PR TITLE
Initial Contourf test pattern.

### LINKED ISSUE #28: test contourf
@bjlittle what do you think might be a minimal useful test? following #19

I suggest
`lib/cube_browser/tests/unit/test_Contourf.py`
as a new test file

### PR DESCRIPTION
**Pull request by bjlittle**
Closes #28

### CODE REVIEW

**Comment by marqh** [comment]
> Coverage increased (+39.8%) to 74.038%

good score ;)

**Comment by bjlittle** [comment]
Something is better than nothing, right? :wink:

**Comment by marqh** [comment]
this looks great; i'm going to merge this and work from it

excellent stuff

**Comment by bjlittle** [comment]
Nice, thanks @marqh

**Pull request merged**
