### PR TITLE
2for

### PR DESCRIPTION
**Pull request by marqh**
explorer for two plots, a and b

### CODE REVIEW

**Comment by corinnebosley** [comment]
I'm having some problems with this.  Do you want discussion yet or are you still working on it?

**Comment by marqh** [comment]
@corinnebosley 
still a couple of failing tests to fix, but explorer is functional and ready for further comment

**Comment by corinnebosley** [comment]
@marqh Still having problems with this.  No colour in the plot again, and this time I scrolled down far enough to see an error that says this:

"AttributeError: 'module' object has no attribute 'SelectionSlider'"

Pete got the same error this morning when he tried to run the master version of explorer.

**Comment by corinnebosley** [comment]
@marqh  Functionality and layout is much better, everything works fine with addition of traits.  

All this needs is some in-line documentation I think.  Maybe some clarity on behaviour of tabs as well (i.e. if you choose more than two, some of them will be discarded when you come to plot because you can only choose two subplots).

Do you want me to merge this so you can think about adding some docs in another PR?

**Comment by marqh** [comment]
> Do you want me to merge this so you can think about adding some docs in another PR?

hold off for one more commit

**Comment by marqh** [comment]
> Do you want me to merge this so you can think about adding some docs in another PR?

i think this work is sensible and should be a new PR

**Comment by corinnebosley** [comment]
OK, I am happy.

**Comment by corinnebosley** [comment]
@marqh Did you want me to squash the commits or leave them unsquashed?

**Comment by marqh** [comment]
leave the commits please
ta

**Pull request merged**
