### PR TITLE
Contour skeleton

### PR DESCRIPTION
**Pull request by corinnebosley**

### CODE REVIEW

**Comment by corinnebosley** [comment]
@bjlittle You got time to take a look at this for me?

**Comment by bjlittle** [comment]
@corinnebosley Hang tight, I'll get on it asap ...

Shame our test coverage has taken a nose dive :hankey:

**Comment by corinnebosley** [comment]
@bjlittle I have merged the refactoring that Mark and I have just done into this pull request, if you fancy having a peek. 

See you Friday.

**Comment by bjlittle** [comment]
Will do, thanks!

**Pull request merged**
