### PR TITLE
pcolormesh class added

### PR DESCRIPTION
**Pull request by corinnebosley**
Method works, but I am not entirely happy that it contains the variable on line 193 called self.qcs (quad contour set) when it actually uses a quad mesh.

This will have to be changed at some point for clarity and accuracy, but as far as functionality is concerned, this is a trivial issue and makes no difference to the outcome of the call.

### CODE REVIEW

**Comment by corinnebosley** [comment]
closes #14

**Comment by corinnebosley** [comment]
That doesn't seem right, I'm sure that was meant to link some things up...

**Comment by marqh** [comment]
> That doesn't seem right, I'm sure that was meant to link some things up...

it will when we close it, it's fine

**Comment by marqh** [comment]
suggestion:

take line
https://github.com/corinnebosley/cube_browser/blob/0a462d171f4da3b5d6e870a52afd4fb9a63bb38a/lib/cube_browser/__init__.py#L38

'remove' this line; it is what mandates the shared behaviour

now only contour and contourf have this behaviour, and only on `__call__`

then you can change 
https://github.com/corinnebosley/cube_browser/blob/0a462d171f4da3b5d6e870a52afd4fb9a63bb38a/lib/cube_browser/__init__.py#L193

to something like
```
# add QuadMesh to self
self.qm = ...
```

mebbe add comment to this behaviour in contour/contourf
```
# add ContourSetQuadContourSet to self
```

**Comment by marqh** [comment]
see #45 for a suggested pattern for testing.  if you like it, i suggest you merge it, then rebase this branch onto the new master
(there should be no conflicts)

you can then add a new test module for pcolormesh following the pattern

**Comment by corinnebosley** [comment]
OK, just worked out how to rebase properly (sorry, still getting my head around doing that without breaking stuff), so how much do I have to change in the test module?

**Comment by corinnebosley** [comment]
Never mind, I am going home soon, I will have a look at this on Monday when I get in.  I'm sure I can work it out, but I seem to have a bit of a stupour on today.  Not achieved nearly as much as I wanted to.

Everything is fine.  

I will be capable and productive again on Monday and get stuff done.

**Comment by marqh** [comment]
i suggest adding a new file, called `test_Pcolormesh.py` in
`tests/unit/`

i think it should be able to be very similar to 
https://github.com/SciTools/cube_browser/blob/master/lib/cube_browser/tests/unit/test_Contour.py

search and replace, then fix 
https://github.com/SciTools/cube_browser/blob/master/lib/cube_browser/tests/unit/test_Contour.py#L26

(... i think)

**Comment by corinnebosley** [comment]
Coolio.  Thanks

**Comment by marqh** [comment]
:)

**Comment by marqh** [comment]
i don't understand why travis is failing this test, it looks good to me

@corinnebosley does the teat pass locally?
```
python test_Pcolormesh
```

@bjlittle can you see why the test runner is failing to find this test despite knowing to look for it?

**Comment by corinnebosley** [comment]
@marqh I think this was a small error in an import.  I had assumed that if QuadContourSet came from matplotlib.contour, then QuadMesh would come from matplotlib.pcolormesh, but it comes from matplotlib.collections (and mpl.pcolormesh doesn't exist).

I've got my fingers crossed.

**Pull request merged**
