### PR TITLE
Plot-type coords default and checking.

### PR DESCRIPTION
**Pull request by bjlittle**
Early bird, and still to do ...
- [x] unit test coverage

### CODE REVIEW

**Comment by bjlittle** [comment]
@marqh and @corinnebosley heads-up ...

**Comment by corinnebosley** [comment]
Thank you @bjlittle , I am happy.

**Comment by marqh** [comment]
OK; i'm still having significant concerns about setting defaults for coords.  I am quite tempted to reopen this discussion, particualrly given our view that axes must be provided

however, I want to move on swiftly, so I'm going to merge this, then consider removing the functionality later, rather than hold things up on this point

**Comment by bjlittle** [comment]
@marqh Duly noted, thanks :wink:

**Comment by bjlittle** [comment]
@marqh Reference [iris.plot._get_plot_defn](https://github.com/SciTools/iris/blob/master/lib/iris/plot.py#L135-L194)

**Pull request merged**
