### PR TITLE
Test pattern

### PR DESCRIPTION
**Pull request by marqh**
testing for contour contourf and pyplot

### CODE REVIEW

**Comment by marqh** [comment]
a feature i have recently discovered:

when one presses `Merge pull request` the next merge button have a drop down menu
in this menu, you can choose to 'squish these commits into a single commit'

thus you don't have to have the 'please squish' palaver

ty gh

**Comment by marqh** [comment]
@corinnebosley do you think this pattern makes sense?
do you think you would merge it?

**Comment by corinnebosley** [comment]
Let me just have a look...

**Comment by corinnebosley** [comment]
That looks fine to me.  I am happy to merge.

**Pull request merged**
