### PR TITLE
Report test coverage.

### PR DESCRIPTION
**Pull request by bjlittle**
Automated reporting of cube-browser test coverage, see https://coveralls.io/

### CODE REVIEW

**Comment by corinnebosley** [comment]
nice.

**Comment by bjlittle** [comment]
@corinnebosley Why, thank-you :blush: ... fancy owning it with a view to merging? 

Would be super handy at this end :pray:

**Comment by bjlittle** [comment]
Hoo-rah! It lives :smile:

**Comment by corinnebosley** [comment]
Does this need to go into review before I can merge it? My trigger finger is getting twitchy.

**Comment by corinnebosley** [comment]
Yeah!

**Comment by bjlittle** [comment]
Boom! Awesome! Thanks @corinnebosley

**Pull request merged**
